[package]
name = "t57"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
bytes = "1.5.0"
chrono = "0.4.35"
crossterm = "0.27.0"
hex = "0.4.3"
ratatui = "0.26.1"
ringbuffer = "0.15.0"
serialport = "4.3.0"
